//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ESantiagoFhLogisticaEntities : DbContext
    {
        public ESantiagoFhLogisticaEntities()
            : base("name=ESantiagoFhLogisticaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Equipo> Equipo { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioEquipo> UsuarioEquipo { get; set; }
    
        public virtual ObjectResult<UsuarioEquipoGetAll_Result> UsuarioEquipoGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioEquipoGetAll_Result>("UsuarioEquipoGetAll");
        }
    
        public virtual ObjectResult<EquipoGetEquiposSinAsignar_Result> EquipoGetEquiposSinAsignar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EquipoGetEquiposSinAsignar_Result>("EquipoGetEquiposSinAsignar");
        }
    
        public virtual ObjectResult<UsuarioGetUsuariosSinEquipo_Result> UsuarioGetUsuariosSinEquipo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioGetUsuariosSinEquipo_Result>("UsuarioGetUsuariosSinEquipo");
        }
    
        public virtual ObjectResult<UsuarioGetAll_Result> UsuarioGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioGetAll_Result>("UsuarioGetAll");
        }
    
        public virtual ObjectResult<UsuarioGetById_Result> UsuarioGetById(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioGetById_Result>("UsuarioGetById", idUsuarioParameter);
        }
    
        public virtual int UsuarioEquipoAdd(Nullable<int> idUsuario, Nullable<int> idEquipo)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idEquipoParameter = idEquipo.HasValue ?
                new ObjectParameter("IdEquipo", idEquipo) :
                new ObjectParameter("IdEquipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UsuarioEquipoAdd", idUsuarioParameter, idEquipoParameter);
        }
    
        public virtual int UsuarioEquipoDelete(Nullable<int> idUsuario, Nullable<int> idEquipo)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idEquipoParameter = idEquipo.HasValue ?
                new ObjectParameter("IdEquipo", idEquipo) :
                new ObjectParameter("IdEquipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UsuarioEquipoDelete", idUsuarioParameter, idEquipoParameter);
        }
    
        public virtual ObjectResult<EquipoGetEquiposSinAsignarByIdMarcaAndIdTipo_Result> EquipoGetEquiposSinAsignarByIdMarcaAndIdTipo(Nullable<int> idMarca, Nullable<int> idTipo)
        {
            var idMarcaParameter = idMarca.HasValue ?
                new ObjectParameter("IdMarca", idMarca) :
                new ObjectParameter("IdMarca", typeof(int));
    
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("IdTipo", idTipo) :
                new ObjectParameter("IdTipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EquipoGetEquiposSinAsignarByIdMarcaAndIdTipo_Result>("EquipoGetEquiposSinAsignarByIdMarcaAndIdTipo", idMarcaParameter, idTipoParameter);
        }
    
        public virtual ObjectResult<MarcaGetAll_Result> MarcaGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarcaGetAll_Result>("MarcaGetAll");
        }
    
        public virtual ObjectResult<TipoGetAll_Result> TipoGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TipoGetAll_Result>("TipoGetAll");
        }
    
        public virtual int UsuarioEquipoUpdate(Nullable<int> idUsuario, Nullable<int> idEquipo)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idEquipoParameter = idEquipo.HasValue ?
                new ObjectParameter("IdEquipo", idEquipo) :
                new ObjectParameter("IdEquipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UsuarioEquipoUpdate", idUsuarioParameter, idEquipoParameter);
        }
    }
}
